### ISSUE TITLE
Convert to using the PEP 8 style guide

### ISSUE THREAD

**Issue by Nihilate** [Nihilate/Roboragi#16]
All files, functions and variables should follow the recommended Python style guide (PEP 8).

**Comment by reillysiemens** [comment]
@Nihilate: I'm happy to take this one if you want to assign it to me. I think it'll help make the other issues in this project a little easier to tackle.

**Comment by Nihilate** [comment]
Sounds good to me, go ahead :)

**Comment by reillysiemens** [comment]
FWIW, I think that once the majority of PEP8 violations are taken care of then linting should be added as a CI step to keep the code from regressing in that regard.

**Comment by Nihilate** [comment]
Definitely. I've added #53 to add a code coverage report (failing the build on low coverage might not be an option given how low it is at the moment) and #54 to add linting (with failures on regression).

**Comment by reillysiemens** [comment]
Hey, @Nihilate, I did some work on this last year, but since then I've come to really enjoy using [Black](https://pypi.org/project/black/) to just format code. Would you be amenable to closing this issue in favor of resolving all style issues through auto-formatting? I'd be happy to open an issue and submit a corresponding PR if that sounds good to you.

**Comment by Nihilate** [comment]
Hey! Sounds reasonable to me - I've been using [RuboCop](https://github.com/rubocop-hq/rubocop) at work and the auto-formatter for that has been really useful. I'll open another issue.

**Comment by Nihilate** [comment]
I've created a new enhancement over here: https://github.com/Nihilate/Roboragi/issues/73
