### ISSUE TITLE
Score

### ISSUE THREAD

**Issue by NatoBoram** [Nihilate/Roboragi#8]
Wouldn't it be nice if it displayed the score of an anime?

Example :

> This anime has a score of 89%. It is great!

> This anime has a score of 56%. It's average.

More compact format could also be used. For example : `[60%] Good`

**Comment by Nihilate** [comment]
I'm not a huge fan of adding scores to be honest. From a conceptual level I kind of like that Roboragi just links information and that it's up to the requester to give context ("I like {this show} because the characters are interesting and it's got a cool art style" over "Watch {this show}" and a score). I feel like adding a score right to the reply will make it more likely for someone to judge something as being bad before even clicking the link, even if it might be something they get into when they take a closer look.

On a more technical level, there's a question around which site(s) to use for scores and, if multiple end up being used, how to average them out. I'm not so sure on the data quality either - it feels like 80% of MAL scores sit at around 7.5 for example :P

**Comment by NatoBoram** [comment]
Yeah, *mean values* are very high on MAL. One way to average them out would be by weighting the number of reviews (if this data is available).
